# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 09:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('img_url', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
